services:
  keydb:
    image: eqalpha/keydb:alpine_x86_64_v6.3.4
    ports:
      - "6379:6379"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - keydb
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - ${STORAGE}:/app/storage
    environment:
      - PORT=${PORT}
      - STORAGE=${STORAGE}
    command: ["go", "run", "./cmd/server/main.go", "-port", "${PORT}", "-storage", "${STORAGE}"]

volumes:
  keydb-data: